### ISSUE TITLE
Under the window computer, `npm install qjsc -g` error

### ISSUE THREAD

**Issue by YeWills** [openkraken/node-qjsc#11]
Under the window computer, I run the command: 

`npm install qjsc -g`

Errors are reported as follows，Please help solve it. Thank you very much:
```s
PS D:\git\hellow-webpack\min\bk-mwebpack> npm i qjsc -g
C:\Program Files\nodejs\qjsc -> C:\Program Files\nodejs\node_modules\qjsc\bin\qjsc.js

> qjsc@0.2.10 install C:\Program Files\nodejs\node_modules\qjsc
> node install.js

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python39\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python39\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python39-32\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python38\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python38\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python38-32\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python37\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python37\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python37-32\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python36\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python36\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\YeWills\AppData\Local\Programs\Python\Python36-32\python.exe
gyp ERR! find Python - "C:\Users\YeWills\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
gyp ERR! find Python checking if the py launcher can be used to find Python 3
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\YeWills\AppData\Roaming\nvm\v14.17.6\node_modules\node-gyp\lib\find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\YeWills\AppData\Roaming\nvm\v14.17.6\node_modules\node-gyp\lib\find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\YeWills\AppData\Roaming\nvm\v14.17.6\node_modules\node-gyp\lib\find-python.js:228:18)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\YeWills\AppData\Roaming\nvm\v14.17.6\node_modules\node-gyp\lib\find-python.js:294:16)
gyp ERR! stack     at exithandler (child_process.js:397:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:409:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\YeWills\\AppData\\Roaming\\nvm\\v14.17.6\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\qjsc
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qjsc@0.2.10 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qjsc@0.2.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\YeWills\AppData\Roaming\npm-cache\_logs\2022-03-09T10_12_44_419Z-debug.log
```

**Comment by wssgcg1213** [comment]
You may need a python installation as tips.
