### ISSUE TITLE
Miss stdatomic.h on webide server

### ISSUE THREAD

**Issue by dickeylth** [openkraken/node-qjsc#8]
```shell
[4/12] scripts.install @ali/builder-clam-rx@1.8.21 › @ali/clam-plugin-rax-build@1.8.21 › rax-app@3.8.11 › build-plugin-rax-kraken@2.1.0 › qjsc@^0.2.4 run "node-gyp-build", root: "/home/admin/.clam/@ali/clam-toolkit-rx/package/node_modules/_qjsc@0.2.5@qjsc"
make: 进入目录“/.../package/node_modules/_qjsc@0.2.5@qjsc/build”
  CXX(target) Release/obj.target/qjsc_20210327/src/qjsc_20210327.o
  CC(target) Release/obj.target/qjsc_20210327/deps/quickjs_2021_03_27/cutils.o
  CC(target) Release/obj.target/qjsc_20210327/deps/quickjs_2021_03_27/libregexp.o
  CC(target) Release/obj.target/qjsc_20210327/deps/quickjs_2021_03_27/libunicode.o
  CC(target) Release/obj.target/qjsc_20210327/deps/quickjs_2021_03_27/quickjs.o
../deps/quickjs_2021_03_27/quickjs.c:146:23: 致命错误：stdatomic.h：没有那个文件或目录
 #include <stdatomic.h>
                       ^
编译中断。
make: *** [Release/obj.target/qjsc_20210327/deps/quickjs_2021_03_27/quickjs.o] 错误 1
make: 离开目录“/.../node_modules/_qjsc@0.2.5@qjsc/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.../nvm/versions/node/v14.17.6/lib/node_modules/tnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.9.151-015.ali3000.alios7.x86_64
gyp ERR! command "/.../nvm/versions/node/v14.17.6/bin/node" "/.../nvm/versions/node/v14.17.6/lib/node_modules/tnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /.../node_modules/_qjsc@0.2.5@qjsc
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 
[npminstall:runscript:error] ... › rax-app@3.8.11 › build-plugin-rax-kraken@2.1.0 › qjsc@^0.2.4 scripts.install run "node-gyp-build" error: Error [RunScriptError]: Run "sh -c node-gyp-build" error, exit code 1
    at ChildProcess.<anonymous> (/.../nvm/versions/node/v14.17.6/lib/node_modules/tnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  stdio: [Object],
  exitcode: 1
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node-gyp-build" error, exit code 1
```

**Comment by dickeylth** [comment]
应该跟服务器 centos 7 用的 gcc 版本 4.8.5 比较老有关系

**Comment by andycall** [comment]
使用 0.2.7 以上版本可以解决这个问题。
